import React from 'react';
import cv_image from "../assets/image/cv_image.png";
import { Contact_data } from '../data';

const Home = () => {

    return (
        <section className='home-section'>
            <div className="home-wrapper">
                <svg xmlns="http://www.w3.org/2000/svg" style={{display:"none"}}>
                    <defs>
                        <filter id="kennedy-comp-isuax1ud" color-interpolation-filters="sRGB">
                            <feComponentTransfer result="srcRGB">
                                <feFuncR type="linear" slope="1.1" intercept="-0.05"></feFuncR>
                                <feFuncG type="linear" slope="1.1" intercept="-0.05"></feFuncG>
                                <feFuncB type="linear" slope="1.1" intercept="-0.05"></feFuncB>
                            </feComponentTransfer>
                            <feColorMatrix type="saturate" values="0"></feColorMatrix>
                            <feComponentTransfer>
                                <feFuncR type="linear" slope="0.9"></feFuncR>
                                <feFuncG type="linear" slope="0.9"></feFuncG>
                                <feFuncB type="linear" slope="0.9"></feFuncB>
                            </feComponentTransfer>
                        </filter>
                    </defs>
                </svg>
                <div className="bg-image">
                </div>
                <div className="contact-wrapper d-flex">
                    <div className="contact-image">
                       <div className='image'> <img src={cv_image} alt="cv-image" style={{ filter: "url(#kennedy-comp-isuax1ud)" }}/></div>
                    </div>
                    <div className="contact-info">
                        <div className="profile-box d-flex">
                            <h4 className='name'>Zarifa Nasirova</h4>
                            <h6 className='role'>Front-End Developer</h6>
                        </div>
                        <ul>
                            {
                                Contact_data.map(item => (
                                    <li className='d-flex'><span>{item.type}</span> <span>{item.value}</span></li>
                                ))
                            }
                        </ul>

                    </div>
                </div>
            </div>

            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>

            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
            <div>salam</div>
        </section>
    )
}

export default Home